### ISSUE TITLE
Laminar no longer recognizes links

### ISSUE THREAD

**Issue by Cynerd** [ohwgiles/laminar#69] opened 2018-10-14 15:16 UTC
In Laminar version 0.6 there was a possibility to use links in `run` directory instead of plain files. I was using this to have generic templates. Creating new specific job was just a case of creating link and providing specific configuration in `*.env` file. In current master this is broken. As it seems Laminar is able to found job it self but it won't load `*.conf` nor `*.env` file (link).

Command `laminarc show-jobs` is also affected.

**Comment by ohwgiles** [comment] 2018-10-14 19:17
I always intended that symlinks could be used for this. Thanks for catching this regression, should be fixed now.

**Closed** 2018-10-14 19:16 UTC
