### ISSUE TITLE
executors question

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#46] opened 2018-04-30 07:29 UTC
I have:
```
nodes/default.conf
EXECUTORS=2

```
```
nodes/emerge.conf
EXECUTORS=1
TAGS=emerge

```
but laminar spins up 3 jobs for a job tagged emerge using jobs/job.conf

Am I using it wrong? 

Thank you

**Comment by ohwgiles** [comment] 2018-05-01 08:25
This is the current expected behaviour, though I agree that it's not necessarily the most intuitive. The [Nodes and Tags](https://github.com/ohwgiles/laminar#nodes-and-tags) section describes this:
> If a node has tags, only jobs with a matching tag will be executed on it. If a node has no tags, it will accept any job.

The logic is implemented here: https://github.com/ohwgiles/laminar/blob/master/src/laminar.cpp#L555-L576

You might expect that if a job has a tag, it should *only* run on nodes with a matching tag. However, since the tags are also used to group jobs in the UI, not just bind to nodes, I did it this way to cover the common case where the admin only wants to group in the UI and doesn't need to define nodes. Suggestions welcome for a better way to provide this functionality...

**Comment by palica** [comment] 2018-05-01 18:46
hm, so I want to limit cpu intensive tasks. if I leave default node with 10 jobs and cpu intensive with only 1, laminar would still launch 11 cpu intensive task - is that correct?

I will have to think about it, but it then makes sense in my case to limit default to 0 and assign tags to everything.

**Comment by ohwgiles** [comment] 2018-05-02 04:58
> hm, so I want to limit cpu intensive tasks. if I leave default node with 10 jobs and cpu intensive with only 1, laminar would still launch 11 cpu intensive task - is that correct?

Correct.

> limit default to 0 and assign tags to everything.

If you make `default` have zero executors then it's the same as removing it altogether. But yes, you would need to assign tags to everything.

I'm starting to think this is a bit of a design flaw in the nodes/tags system, but I'm not sure what's the best way around it. The only obvious thing would be to have a `NODES=` option in each job config, and use the tags only for grouping in the UI. The problem with that is that you would lose the nice feature there exists now of adding a new node to an existing tag so all jobs tagged with it would automatically run on it. I suppose this could be worked around by allowing `NODES=` to have a wildcard `*` in it or something.

Or alternatively, keep nodes and tags as they are and change the behaviour so that a tagged job won't run on a tagless node, and move the UI grouping to a new config option like `UIGROUPS=` or something, or even think of a different way to manage the groups.

Any thoughts on this?

**Comment by ohwgiles** [comment] 2018-09-08 18:14
Closing as for now I have no plans to change how this works

**Closed by ohwgiles** 2018-09-08 18:14 UTC
Labels: question
