### ISSUE TITLE
Raspberry Pi packages?

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#73] opened 2018-11-24 12:55 UTC
Hello!

I've got a Raspberry Pi, and laminar looks like just the thing I'm after - as other continuous-integration tool  look way too heavy. 

Unfortunately, I've run into a number of issues attempting to build from source - and there don't appear to be any binary packages available for `armhf` / `armv7l`.

Is there any possibility of Raspberry-Pi-compatible binaries?

**Comment by ohwgiles** [comment] 2018-11-24 14:58
Hi, welcome to laminar. I can probably get some binaries together for raspberry pi. Of course a package depends on more than just the hardware; can I assume you're running Raspbian Stretch?

cc @kisik21 because I think they mentioned running laminar on gentoo on an rpi

**Comment by kisik21** [comment] 2018-11-24 16:35
I'm actually running a quite old version of Laminar as I haven't updated my RPi as often as I should. Currently I am planning to switch to NixOS - and when I do, it will be pretty easy for me to work out a build process on ARM, as NixOS makes binaries reproducible.

**Comment by sbrl** [comment] 2018-11-24 19:53
Hey, thanks for the reply! Yeah - I'm running standard Raspbian Stretch with all patches applied - and my plan is to keep up-to-date with the latest version going forwards, @ohwgiles.

Laminar seems like a great fit for the _Raspberry Pi_, since it's so lightweight :-)

**Comment by ohwgiles** [comment] 2018-11-28 19:11
I don't have a pi to test on, could you try this package and let me know how it goes?

[laminar-test-rpi-deb.tar.gz](https://github.com/ohwgiles/laminar/files/2626255/laminar-test-rpi-deb.tar.gz)

**Comment by kisik21** [comment] 2018-11-30 02:42
@ohwgiles this is a debian package. I'm running Gentoo. Can you just package it as .tar.xz?

**Comment by ohwgiles** [comment] 2018-11-30 05:58
Sorry I should have mentioned this is for @sbrl to try on Raspbian. Correspondingly it's linked against the versions of zlib, sqlite and glibc that are provided by that OS (actually Debian Stretch).

It might work on Gentoo if those libraries are ABI-compatible. If you want to try this, you can easily extract the `.tar.xz` from a `.deb` file using `ar x $debfile data.tar.xz`.

Eventually it would be great if laminar were packaged in distros' official repositories, but this will need support from people inside the respective OS packaging community. I don't really know anything about Gentoo or NixOS, but I'm of course happy to support any packaging effort for those distros.

**Comment by sbrl** [comment] 2018-11-30 08:13
Hey! I've tested it and it looks to be working fabulously, @ohwgiles :smiley_cat:

Is there any chance of supporting ANSI escape codes (say for colour) in the output console in the web interface? With my particular difficulties parsing of the colour that my build script outputs would make the whole thing much easier to visually parse.

**Comment by ohwgiles** [comment] 2018-11-30 13:50
@sbrl good to hear. I'll commit the script used to build the package as a resolution to this issue. Regarding ANSI colours, this should work already (last fixed in #25). Typically, the build tool doesn't print the colours if it isn't connected to a terminal, and this needs to be overridden with a tool-specific command-line argument or environment variable. Please raise a separate issue if you find an issue on Laminar's side regarding this.

@seifertm , @palica a quick google suggests that one can upload ebuilds to packages.gentoo.org. If this is the accepted way to share packages with other Gentoo users then it would be awesome if someone could submit those, then we can point new users there from the README/UserManual. @kisik21 similarly with NixOS sometime maybe? I maintain the [AUR package](https://aur.archlinux.org/packages/laminar/) but I'm not comfortable contributing packages for distros I don't use....anyway if anyone is interested in helping with this please don't hesitate to open a new issue to discuss that.

Thanks everyone

**Closed** 2018-11-30 13:56 UTC
Labels: question

**Comment by sbrl** [comment] 2018-11-30 17:53
Oh awesome, @ohwgiles! I didn't realise that support was implemented already - it didn't looklike it supported it at first glance. I'll try it out - it probably works then :P

Thanks so much for providing the package! Will there be an apt repo / an RSS feed I can subscribe to to keep laminar up to date?

**Comment by ohwgiles** [comment] 2018-11-30 18:16
No apt repo or RSS feed, but you can use github's "watch" feature. Each release will come with a binary package for the current (at time of release) centos x86_64, debian amd64, and now debian armhf (raspbian-compatible)

**Comment by palica** [comment] 2018-11-30 20:24
as for gentoo, you would have to have commit permissions to be able to add
packages to packages.gentoo.org (or better yet to gentoo's portage) and I
don't have those. What we could do is file a bug with ebuild request on
bugs.gentoo.org.

oliver, you could state somewhere the minimal requirements for packages
that are dependencies for laminar. with minimal required version number.

I might file the bug for you so we can have laminar in portage

Greetings to everyone
Pavol

**Comment by kisik21** [comment] 2018-11-30 23:03
I can probably maintain the laminar package for NixOS at least in the overlay (personal repo), but probably will be able to make a PR to nixpkgs (main repo) and become a maintainer. But first I need to finish the build on my Raspberry Pi.
