### ISSUE TITLE
Small tweak to laminar.service

### ISSUE THREAD

**Issue by cweagans** [ohwgiles/laminar#117] opened 2020-03-10 18:38 UTC
We did our Laminar rollout recently and had to make a small tweak to the Laminar service file. Sharing here in case it's helpful:

```
[Unit]
Description=Laminar continuous integration service
After=network.target

[Service]
User=laminar
EnvironmentFile=-/etc/laminar.conf
ExecStart=/usr/sbin/laminard
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

It's just the Restart/RestartSec params. I think it was an issue with my PR to add customizable index.html functionality -- after a while it crashed with:

> Mar 10 11:08:26 ci laminard[2481]: fatal: ::read(fd, buffer, maxBytes): Connection reset by peer

Worked just fine after starting back up again though, so we just added a restart policy to keep things moving until the next Laminar release when the updated version of that functionality is included.

**Comment by ohwgiles** [comment] 2020-03-10 19:31
> Mar 10 11:08:26 ci laminard[2481]: fatal: ::read(fd, buffer, maxBytes): Connection reset by peer

This looks like a real bug, it's unlikely to be caused by your customizable index.html PR. If you find how to reproduce this reliably please let me know

**Comment by ohwgiles** [comment] 2020-07-05 00:47
Closing for now, please reopen if you can reproduce this issue. `journalctl -u laminar` might contain some interesting information....

**Closed by ohwgiles** 2020-07-05 00:47 UTC

**Comment by cweagans** [comment] 2020-07-05 05:37
We haven't run into this recently. It's probably still a good idea to have some Restart params in the service file though. I think it's reasonable to assume that anyone that's running Laminar via systemd will _always_ want it running, so restarting is a pretty sane default.

**Comment by ohwgiles** [comment] 2020-07-06 04:15
I agree most sysadmins will probably want to set this. It protects production systems against outages, but if there is a real bug in Laminar, I want it to be discovered so it can be fixed, so I don't want it hidden by default.
