### ISSUE TITLE
please add ability to set more details for graphs

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#66] opened 2018-09-09 12:41 UTC
I like the new graphs a lot! Thanks for implementing those.

The question now is if you want to add more control to the graphs or if one should use another tool for the graphical representation of jobs.

![image](https://user-images.githubusercontent.com/3177786/45264417-79d77180-b43c-11e8-9469-26d7e131c453.png)

For example this would be nice to be able to **show jobs per hour**. This would allow to see the average job/hour on a particular node. Or just make the time range user adjustable.

![image](https://user-images.githubusercontent.com/3177786/45264441-c3c05780-b43c-11e8-98c6-a7a7c1e2bcb1.png)
In my usage example I run a meta-job that starts couple of hundred jobs and the whole job run takes about a day to complete and such the job/24 hours is not showing any valuable information. Would this be again possible to add custom time range like number of jobs last x days. (but of course that wouldn't change anything for my example).

![image](https://user-images.githubusercontent.com/3177786/45264479-5d880480-b43d-11e8-8946-ebc55085017d.png)
It would be nice to be able to group the results maybe by date. So you could see what regressions happened at what date? Does that make sense?

![image](https://user-images.githubusercontent.com/3177786/45264503-ebfc8600-b43d-11e8-9e48-259f2bfff981.png)
Here a general availability to be able to display even more data inside the graph. So like a visualisation page where you could see all the jobs pass rates. Maybe even for all graphs as an option.

![image](https://user-images.githubusercontent.com/3177786/45264516-2c5c0400-b43e-11e8-8644-8e69c146d7c2.png)
I don't understand this graph that much. If you can explain what gets graphed, please.

![image](https://user-images.githubusercontent.com/3177786/45264525-56152b00-b43e-11e8-8914-695f8bebe9d7.png)
I like this one. Maybe display the time in different units?

Thanks for all your time and code!

**Comment by palica** [comment] 2018-09-09 12:51
I think I am spoiled by ElasticSearch and Kibana interface. If none of this is possible or easy to add. Would you consider maybe adding some env variables that would be part of the job and one would be able to submit them as part of the result.

I would be interested in 
JOB_DURATION
JOB_LASTDURATION
JOB_STARTDATE

Maybe some more? I can't think of anything else.

**Comment by ohwgiles** [comment] 2018-09-10 08:31
Everything is possible, how easy it is depends on quite a few things. Rather than making everything configurable, I'd prefer to spend some effort on coming up with really good defaults that suit the most people, and then documenting how to patch it if anyone really wants something different. I think that adding this "small" kind of configurability for the graphs would have more negative impact on laminar's maintainability and its ease of use than the positives it would bring. Also I'm happy to add features to make it easier to use external graphing/statistics tools.

Your feedback is really excellent and I hope you'll help me improve the graphs for the "typical" case even if it isn't always exactly the same as yours. I agree there are certainly areas for improvement.

Now I'll try to address some of your points specifically:

**Total runs per day this week, adjustable to per hour:** I understand your point, but I think that for the most common cases, per day might be more useful than per hour.

**Most runs per job in last 24 hours:** Increasing or making the time range configurable doesn't look like it will make this graph useful for your use case.

**Regressions and recoveries:** In your screenshot the word "since" is missing between the passing and failing build numbers, which is strange. At the moment they're sorted descending by number of builds between the passing and failing builds (i.e. to emphasize the bulids which have been failing the longest). The problem with grouping by date is that you lose resolution of which actual jobs are failing. I hope that this graph would be used to quickly identify which jobs are failing.

**Low pass rates:** I can't think of any way to visualize this for your case with thousands of jobs. Unless you mean grouping by aggregates, like the final graph?

**Run time changes:** You are right, this graph could be made clearer. What it shows is the 8 jobs with the largest difference between the range and standard deviation of build times, over the last 10 runs. The intention is to identify jobs which have recent outliers in their build time. In your case, for example, the last two builds of `sys-apps--findutils` took about 0 seconds, but the one before that took about 35000 seconds. I need to label the Y axis, but maybe there are other things to do to make this graph clearer?

**Average run time distribution:** Which units would be good for you? Please suggest something (or create a PR ;))

**External tool/exposing environment variables:** I have no experience with Kibana or ElasticSearch but I like the idea of a generic way for Laminar to expose information to other applications. These would be pretty easy to add, except duration, since the duration isn't known until the job is done. I suppose I could instead calculate the duration on just the `.run` script, instead of the total of the `.run` and all the `.after` scripts, so then it would be known for the `.after` script, just like `$RESULT`.

The other option is just to open `$LAMINAR_HOME/laminar.sqlite` directly and make your own queries against it. It's a simple and regular sqlite database, I'm sure there are a bunch of tools that can do some pretty things with that :)

**Comment by palica** [comment] 2018-09-10 09:57
OK.

word since missing - probably due to my custom css
yes labeling the axis would be nice and also use some human readable units on the axis - if under 60 use seconds, if under 3600 use minutes everything else use hours or similar.

same for average runtime distr. ^^^

I might hack that with querying the sqlite directly thanks for the tip.

**Comment by ohwgiles** [comment] 2018-09-28 12:40
@palica I've just pushed f5e719ac02bffceafda9355d4b28a0ea53995333 which improves some of the labelling on the graphs and their axes. I think I'll close this issue for now. If you have any more specific suggestions please open new tickets. Also if you succeeded in creating more useful statistics from the sqlite database please consider sharing your method in case it will be useful for others :)

**Closed by ohwgiles** 2018-09-28 12:40 UTC
Labels: enhancement, question
