### ISSUE TITLE
[Enhancement] Workspace refresh

### ISSUE THREAD

**Issue by jakimfett** [ohwgiles/laminar#100] opened 2019-07-04 17:34 UTC
> Original comment [in #97](https://github.com/ohwgiles/laminar/issues/97#issuecomment-507397364):
> Tangentially, is there a way to trigger some sort of 'purge-and-re-initialize-workspace' function?
> Right now, I've just created a job that does an rm across all the job folders, targeting the workspace, but I'm running into concurrency problems.

and
> @ohwgiles commented:
> Not sure I understand...

I'm looking for a way to easily reset a workspace to the programmatic default.
Eg, wipe the workspace clean and re-run the `<job>.init` script.

Right now, I use a `laminar` job that performs `rm -rf ~/app/run/*/workspace`, which wipes out *all* my workspaces, but works well enough while I testbed my pipeline.

What I'd like is something like `laminarc refresh <jobname>` that purges and re-initializes the workspace, warns me if the git repo isn't clean, and gives me a `--force` flag to ignore the state of the directory.

Thoughts?

**Comment by jakimfett** [comment] 2019-07-04 18:03
Functional use case is:
When configuring a new job and `<job>.init` fails to complete all steps, the `workspace` directory exists (preventing `<job>.init` from executing again), but future runs will fail until the directory is manually removed.

**Comment by ohwgiles** [comment] 2019-07-05 17:32
Perhaps a better way to address your functional use case: Laminar should probably delete the `workspace` directory it created if the `.init` script fails. Would this solve your problem?

By the way, you could implement your `refresh` idea easily with a job parameter: `laminarc start refresh for_job=<jobname>`, with `refresh.run` containing `rm -rf $LAMINAR_HOME/run/$for_job/workspace`

**Comment by jakimfett** [comment] 2019-07-06 14:46
> @ohwgiles commented:
> ...delete the workspace directory it created if the .init script fails...

That solves the first (half?) part of my use case.

> ohwgiles commented:
> ...you could implement your refresh idea easily with a job parameter...

Oh, shiney. I'll give that a shot, that level of targeted purge is exactly what my workflow needs.

---
The thought in my mind was something akin to the functionality of `git reset --hard HEAD`, where a single (builtin?) command returns the workspace (and job execution) to a 'pristine' state, useful for when the workspace has manual edits for example.

**Comment by ohwgiles** [comment] 2019-07-06 17:38
> That solves the first (half?) part of my use case.

What's missing? If the `workspace` directory is deleted, each new attempt to run the job will attempt to create the workspace again (and run the `.init` script) until it succeeds

> returns the workspace (and job execution) to a 'pristine' state, useful for when the workspace has manual edits for example.

Manual edits in the workspace raises mental red flags. Its ideal use is read-only content, because as soon as you write you have to be very careful with concurrency (assuming you allow multiple instances of one job to run simultaneously) and with reproducibility (because it's not always easy to track back who changed the workspace when). If it's not large, you can always `cp -r` it to the run directory at the start of the run. If your modifications are all via tools that create new inodes, you could use a fast hard-link copy with `cp -al` to get copy-on-write semantics. Crazier solutions might involve setting up a FUSE overlayfs in your run directory, so changes are isolated to the rundir. Obviously all depends on your workflow

**Comment by jakimfett** [comment] 2019-07-06 19:14
> @ohwgiles commented:
> What's missing?

The check for successful `.init` completion fixes my immediate development problem (eg, setting up new jobs results in a lot of failing builds as I set up the job, and therefor a lot of `rm workspace` as a result.

What's missing is that the `.init` failing is only part of why having the ability to purge a workspace is useful.

> @ohwgiles also commented:
> Manual edits in the workspace...

I very much agree that manual edits are an antipattern I'd like to avoid.

However, in the real world, where the client is proudly showing me their refurbished eMachines box where all of Live exists, and none of the code is version controlled, the first few days of a new project involve a *lot* of manual edits in places that really really would best be avoided.

It's bad. [It's horrible](https://www.stilldrinking.org/programming-sucks). It makes me want to [quit](https://pics.jakimfett.com/reactions/peace_out.gif) and become a goat herder.

I still do it (sysadmin-ing around the cruft), because at the end of the month, I've got the source code autobuilding when committed, and the live infrastructure is functionally immutable post-deployment.

Which is, incidentally, why I want a builtin command that, after having done a bunch of edits to finally make the job work, can wipe "everything" back to automated-as-usual state.

> @ohwgiles also commented:
> ...workflow...

My team has centralized development systems (a repository, a build system, and a frontend test assembly, aka `development`), and a programmatically identical (well, in theory at least...) stack on each workstation (aka `testbed`).

We encourage customization of the `testbed`, with the soft requirement that `development` be fully automated.

So, they checkout the code, make edits, verify tests and compile/packaging/whatever works, commit the code locally, then test it in the local build system.  
If that passes, they push their commits to the centralized repo, and it autobuilds, deploys to dev (on build success), and gets added to the queue for staging next deployment window to `stage`.  

If the local build fails, the developers have the ability to edit their local build environment, including to make changes to the jobfiles (`.run` and `.init`), to ensure that by the time it hits the team centralized development environment, it builds properly and the deployment window is about pushing code, not solving edge cases or environment weirdness.

It's about making the control feedback loop of the development process as tight as possible, and giving each individual developer agency on their `testbed`.

---
Setting up an alias for [the command string you recommended earlier](https://github.com/ohwgiles/laminar/issues/100#issuecomment-508822815) will be easy.

I'd still prefer the commands for managing a workspace to be part of the core utility, rather than a tacked-on hack that may look different on different systems.

**Comment by ohwgiles** [comment] 2019-07-07 08:34
Thanks for your detailed answer, I appreciate the thought you've put into it.

That said, I'm fairly determined about simplicity and anti-patterns in laminar (this is partly why there is no "build now" button); and given that (a) I can't come up with a use case for this feature that I wouldn't consider an anti-pattern, and (b) it is trivially implementable with scripts (you can even directly `rm -rf` as long as the laminar instance is local), all things considered, I don't think it's a good fit for core laminar.

Of course, if you can convince me otherwise I'll happily reconsider; but I think I'll close this for now.

**Closed by ohwgiles** 2019-07-07 08:34 UTC
